apiVersion: batch/v1
kind: Job
metadata:
  name: pomerium-gen-secrets
spec:
  template:
    spec:
      containers:
        - name: gen-secrets
          image: pomerium/ingress-controller:sha-dd49d67@sha256:025570a41e4c67146f6801d99404edac8677434308b259406af49f16bd3e4e25
          imagePullPolicy: IfNotPresent
