apiVersion: batch/v1
kind: Job
metadata:
  name: pomerium-gen-secrets
spec:
  template:
    spec:
      containers:
        - name: gen-secrets
          image: pomerium/ingress-controller:sha-dd49d67@sha256:5c78661d1716a4909ec116cc38d2ab97500d076cf7ea633da585a0057818d3e3
          imagePullPolicy: IfNotPresent
