apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
  namespace: pomerium
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "onearm"
    external-dns.alpha.kubernetes.io/target: "159.69.100.65"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
   

