apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
spec:
  type: NodePort
  externalTrafficPolicy: Local
  externalIPs:
    - 54.187.85.165
    - 35.93.149.90
    - 35.94.189.26
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
      nodePort: 30801  # Specify a nodePort value for TCP traffic on port 443
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
      nodePort: 30803  # Specify a nodePort value for HTTP traffic on port 80
