apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
  namespace: pomerium
  annotations:
    # Reference the variable
    external-dns.alpha.kubernetes.io/hostname: "$(EXTERNAL_DNS_HOSTNAME)"
