apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          imagePullPolicy: IfNotPresent
          image: pomerium/ingress-controller:v0.29.6@sha256:0dfe7cd24722e59c4dcc44a8f17d34387e8193ed66cf1b99f2ab26de94d32cba
          resources:
            limits:
              cpu: 5
              memory: 4Gi
            requests:
              cpu: 300m
              memory: 200Mi
      nodeSelector:
        glueops.dev/role: "glueops-platform"
      tolerations:
        - key: "glueops.dev/role"
          operator: "Equal"
          value: "glueops-platform"
          effect: "NoSchedule" 
