apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  template:
    spec:
      containers:
        - name: pomerium
          imagePullPolicy: IfNotPresent
          image: pomerium/ingress-controller:v0.29.3@sha256:7de344af8bb5c6b7430136b9f9e0f38b03f83626eb61c7802a27510a558db31e
          resources:
            limits:
              cpu: 5
              memory: 4Gi
            requests:
              cpu: 300m
              memory: 200Mi
      nodeSelector:
        glueops.dev/role: "glueops-platform"
      tolerations:
        - key: "glueops.dev/role"
          operator: "Equal"
          value: "glueops-platform"
          effect: "NoSchedule" 
