apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy
spec:
  type: LoadBalancer
  ports:
    - port: 9096
      targetPort: https
      protocol: TCP
      name: https
    - name: http
      targetPort: http
      protocol: TCP
      port: 9095
